package uy.viruscontrol.externalservices.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2020-05-22T13:58:04.704-03:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", name = "IWSPerifericoPrestadoraSalud")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSPerifericoPrestadoraSalud {

    @WebMethod
    @RequestWrapper(localName = "obtenerPrestadorDeSalud", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerPrestadorDeSalud")
    @ResponseWrapper(localName = "obtenerPrestadorDeSaludResponse", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerPrestadorDeSaludResponse")
    @WebResult(name = "return", targetNamespace = "")
    public uy.viruscontrol.externalservices.soap.PrestadoraSalud obtenerPrestadorDeSalud(

        @WebParam(name = "idUsuario", targetNamespace = "")
        int idUsuario
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerPrestadorDeSaludAlternativo", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerPrestadorDeSaludAlternativo")
    @ResponseWrapper(localName = "obtenerPrestadorDeSaludAlternativoResponse", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerPrestadorDeSaludAlternativoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public uy.viruscontrol.externalservices.soap.PrestadoraSalud obtenerPrestadorDeSaludAlternativo(

        @WebParam(name = "idUsuario", targetNamespace = "")
        int idUsuario
    );

    @WebMethod
    @RequestWrapper(localName = "estaDisponible", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.EstaDisponible")
    @ResponseWrapper(localName = "estaDisponibleResponse", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.EstaDisponibleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean estaDisponible(

        @WebParam(name = "idPrestadora", targetNamespace = "")
        int idPrestadora
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerMedicoAsignado", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerMedicoAsignado")
    @ResponseWrapper(localName = "obtenerMedicoAsignadoResponse", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerMedicoAsignadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int obtenerMedicoAsignado(

        @WebParam(name = "idPrestadora", targetNamespace = "")
        int idPrestadora
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerMedicos", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerMedicos")
    @ResponseWrapper(localName = "obtenerMedicosResponse", targetNamespace = "http://soap.ws.drivers.viruscontrol.uy/", className = "uy.viruscontrol.externalservices.soap.ObtenerMedicosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<uy.viruscontrol.externalservices.soap.Medico> obtenerMedicos(

        @WebParam(name = "idPrestadora", targetNamespace = "")
        int idPrestadora
    );
}
