package com.prestadorsalud.services.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2020-05-31T21:08:18.261-03:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://soap.services.prestador.com/", name = "IWSPerifericoPrestadoraSalud")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSPerifericoPrestadoraSalud {

    @WebMethod
    @RequestWrapper(localName = "obtenerPrestadorDeSaludAlternativo", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.ObtenerPrestadorDeSaludAlternativo")
    @ResponseWrapper(localName = "obtenerPrestadorDeSaludAlternativoResponse", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.ObtenerPrestadorDeSaludAlternativoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.prestadorsalud.services.soap.PrestadoraSalud obtenerPrestadorDeSaludAlternativo(

        @WebParam(name = "idUsuario", targetNamespace = "")
        int idUsuario
    );

    @WebMethod
    @RequestWrapper(localName = "estaDisponible", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.EstaDisponible")
    @ResponseWrapper(localName = "estaDisponibleResponse", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.EstaDisponibleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean estaDisponible(

        @WebParam(name = "idPrestadora", targetNamespace = "")
        int idPrestadora
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerMedicoAsignado", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.ObtenerMedicoAsignado")
    @ResponseWrapper(localName = "obtenerMedicoAsignadoResponse", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.ObtenerMedicoAsignadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int obtenerMedicoAsignado(

        @WebParam(name = "idPrestadora", targetNamespace = "")
        int idPrestadora
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerMedicos", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.ObtenerMedicos")
    @ResponseWrapper(localName = "obtenerMedicosResponse", targetNamespace = "http://soap.services.prestador.com/", className = "com.prestadorsalud.services.soap.ObtenerMedicosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.prestadorsalud.services.soap.Medico> obtenerMedicos(

        @WebParam(name = "idPrestadora", targetNamespace = "")
        int idPrestadora
    );
}
