package uy.salud.services.soap.rucaf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2020-05-31T21:06:18.354-03:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://soap.salud.uy/", name = "IRucafService")
@XmlSeeAlso({ObjectFactory.class})
public interface IRucafService {

    @WebMethod
    @RequestWrapper(localName = "obtenerPrestadoraUsuario", targetNamespace = "http://soap.salud.uy/", className = "uy.salud.services.soap.rucaf.ObtenerPrestadoraUsuario")
    @ResponseWrapper(localName = "obtenerPrestadoraUsuarioResponse", targetNamespace = "http://soap.salud.uy/", className = "uy.salud.services.soap.rucaf.ObtenerPrestadoraUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public uy.salud.services.soap.rucaf.PrestadoraSalud obtenerPrestadoraUsuario(

        @WebParam(name = "documento", targetNamespace = "")
        int documento
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerPrestadoras", targetNamespace = "http://soap.salud.uy/", className = "uy.salud.services.soap.rucaf.ObtenerPrestadoras")
    @ResponseWrapper(localName = "obtenerPrestadorasResponse", targetNamespace = "http://soap.salud.uy/", className = "uy.salud.services.soap.rucaf.ObtenerPrestadorasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<uy.salud.services.soap.rucaf.PrestadoraSalud> obtenerPrestadoras()
;
}
